name: PluginLoader
version: 1.0
main: me.akraml.loader.plugin.LoaderPlugin
author: YourName
api-version: 1.13 # Specify a modern API version

commands:
  loader:
    description: Main command for the PluginLoader plugin.
    usage: /<command> sync
    permission: pluginloader.command.sync

permissions:
  pluginloader.command.sync:
    description: Allows the user to run the sync command.
    default: op
